username = ("Владислав")
title = ("Планы")
content = ("То, что нужно сделать")
status = ("Активна")
created_date = ("18-12-2024")
issue_date = ("31-12-2024")
print("Имя пользователя:", username)
print("Заголовок заметки:", title)
print("Описание заметки:", content)
print("Статус заметки:", status)
print("Дата создания заметки:", created_date)
print("Дата истечения заметки:", issue_date)
